version: '3.0'
services:
  imageRecognitionApp:
    image: image_recognition
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - image_recognition_data:/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=imagedb
volumes:
  image_recognition_data:
