springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080

spring:
  application:
    name: ImageRecognition
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/imagedb
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

imagga:
  baseUrl: "https://api.imagga.com/v2"
  user: "acc_ff5a6dec0b5e301"
  password: "21278441ea4e45bd830b9a85aa76e967"
  threshold: 50.0  #This must be a Double value from 1-99.0 (100 will receive no objects)
