springdoc:
  swagger-ui:
    enabled: true

server:
  port: 8080

spring:
  application:
    name: ImageRecognition
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
  datasource:
    url: jdbc:postgresql://postgresqldb:5432/imagedb
    username: postgres
    password: ENC(3FRUj0iBopR7Zv6ZHbyUiYrDJIf/6/sv)
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

jasypt:
  encryptor:
    password: "myHEB"

imagga:
  baseUrl: "https://api.imagga.com/v2"
  user: ENC(ynPGlOTje1j5BTBg/lieHjCCXQvpZSbrnEjduSyQkpw=)
  password: ENC(I85dzFMsZO8Doexa4Ol2kUgjI1+UFujkAeLE/JAuQGJwF1m7uVn3OYmWLFRT41Wq)
  threshold: 50.0  #This must be a Double value from 1-99.0 (100 will receive no objects)
